/* Generated by Yosys 0.36+3 (git sha1 a53032104, aarch64-apple-darwin20.2-clang 10.0.0-4ubuntu1 -fPIC -Os) */

/* top =  1  */
/* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:5.1-19.10" */
module d11_zhexic_i2cdriver(io_in, io_out);
  wire _000_;
  wire _001_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _002_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _003_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _004_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _005_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _006_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _007_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _008_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _009_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _010_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _011_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _012_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _013_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _014_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _015_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _016_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _017_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _018_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _019_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _020_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _021_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _022_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _023_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _024_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _025_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire _026_;
  reg _027_;
  reg _028_;
  reg _029_;
  reg _030_;
  reg _031_;
  reg _032_;
  reg _033_;
  reg _034_;
  reg _035_;
  reg _036_;
  reg _037_;
  reg _038_;
  reg _039_;
  reg _040_;
  reg _041_;
  reg _042_;
  reg _043_;
  reg _044_;
  reg _045_;
  reg _046_;
  reg _047_;
  reg _048_;
  reg _049_;
  reg _050_;
  reg _051_;
  reg _052_;
  reg _053_;
  reg _054_;
  reg _055_;
  reg _056_;
  reg _057_;
  reg _058_;
  reg _059_;
  reg _060_;
  reg _061_;
  reg _062_;
  reg _063_;
  reg _064_;
  reg _065_;
  reg _066_;
  reg _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:6.18-6.23" */
  input [13:0] io_in;
  wire [13:0] io_in;
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:7.19-7.25" */
  output [13:0] io_out;
  wire [13:0] io_out;
  /* hdlname = "mchip clock" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:6.17-6.22" */
  wire \mchip.clock ;
  /* hdlname = "mchip io_in" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:4.24-4.29" */
  /* unused_bits = "11" */
  wire [11:0] \mchip.io_in ;
  /* hdlname = "mchip io_out" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:5.25-5.31" */
  wire [11:0] \mchip.io_out ;
  /* hdlname = "mchip reset" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:7.17-7.22" */
  wire \mchip.reset ;
  /* hdlname = "mchip slv SCL" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:24.18-24.21|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.SCL ;
  /* hdlname = "mchip slv SDA_in" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:22.18-22.24|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.SDA_in ;
  /* hdlname = "mchip slv SDA_out" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:23.18-23.25|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.SDA_out ;
  /* hdlname = "mchip slv clock" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:19.17-19.22|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.clock ;
  /* hdlname = "mchip slv data_in" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:28.24-28.31|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire [7:0] \mchip.slv.data_in ;
  /* hdlname = "mchip slv data_incoming" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:32.19-32.32|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.data_incoming ;
  /* hdlname = "mchip slv data_out" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:29.24-29.32|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire [7:0] \mchip.slv.data_out ;
  /* enum_type = "$enum4" */
  /* hdlname = "mchip slv nextstate" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:233.30-233.39|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire [3:0] \mchip.slv.nextstate ;
  /* hdlname = "mchip slv r1w0" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:212.11-212.15|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.r1w0 ;
  /* hdlname = "mchip slv register_out" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:197.17-197.29|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire [7:0] \mchip.slv.register_out ;
  /* hdlname = "mchip slv reset" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:19.24-19.29|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.reset ;
  /* hdlname = "mchip slv scl_high" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:42.31-42.39|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.scl_high ;
  /* enum_type = "$enum0" */
  /* hdlname = "mchip slv scl_nextstate" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:41.40-41.53|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.scl_nextstate ;
  /* hdlname = "mchip slv sda_high" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:45.31-45.39|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.sda_high ;
  /* enum_type = "$enum1" */
  /* hdlname = "mchip slv sda_nextstate" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:44.40-44.53|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.sda_nextstate ;
  /* hdlname = "mchip slv sipo_out" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:191.17-191.25|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire [7:0] \mchip.slv.sipo_out ;
  /* enum_type = "$enum2" */
  /* hdlname = "mchip slv start_nextstate" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:47.51-47.66|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.start_nextstate ;
  /* enum_type = "$enum3" */
  /* hdlname = "mchip slv stop_nextstate" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:50.49-50.63|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.stop_nextstate ;
  /* hdlname = "mchip slv store" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:196.11-196.16|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.store ;
  /* hdlname = "mchip slv the_piso clock" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:439.29-439.34|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.the_piso.clock ;
  /* hdlname = "mchip slv the_piso data_in" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:438.24-438.31|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire [7:0] \mchip.slv.the_piso.data_in ;
  /* hdlname = "mchip slv the_piso reset" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:439.36-439.41|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.the_piso.reset ;
  /* hdlname = "mchip slv the_reg clock" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:199.14-200.38|d11_zhexic_i2cdriver/src/chip.sv:481.29-481.34|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.the_reg.clock ;
  /* hdlname = "mchip slv the_reg enable" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:199.14-200.38|d11_zhexic_i2cdriver/src/chip.sv:482.29-482.35|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.the_reg.enable ;
  /* hdlname = "mchip slv the_reg in" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:199.14-200.38|d11_zhexic_i2cdriver/src/chip.sv:479.29-479.31|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire [7:0] \mchip.slv.the_reg.in ;
  /* hdlname = "mchip slv the_reg out" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:199.14-200.38|d11_zhexic_i2cdriver/src/chip.sv:480.29-480.32|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire [7:0] \mchip.slv.the_reg.out ;
  /* hdlname = "mchip slv the_reg reset" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:199.14-200.38|d11_zhexic_i2cdriver/src/chip.sv:481.36-481.41|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.the_reg.reset ;
  /* hdlname = "mchip slv the_sipo clock" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:408.29-408.34|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.the_sipo.clock ;
  /* hdlname = "mchip slv the_sipo data_in" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:407.29-407.36|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.the_sipo.data_in ;
  /* hdlname = "mchip slv the_sipo out" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:410.29-410.32|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire [7:0] \mchip.slv.the_sipo.out ;
  /* hdlname = "mchip slv the_sipo reset" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:408.36-408.41|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.the_sipo.reset ;
  /* hdlname = "mchip slv wr_down" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:30.27-30.34|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.wr_down ;
  /* hdlname = "mchip slv wr_up" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:25.18-25.23|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.wr_up ;
  /* hdlname = "mchip slv writeOK" */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:30.18-30.25|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  wire \mchip.slv.writeOK ;
  assign _068_ = ~(_028_ & io_in[13]);
  assign _069_ = _029_ & io_in[13];
  assign _070_ = _068_ & ~(_069_);
  assign _071_ = _031_ & io_in[13];
  assign _072_ = _030_ & io_in[13];
  assign _073_ = _071_ | ~(_072_);
  assign _074_ = _070_ & ~(_073_);
  assign _075_ = _069_ | _068_;
  assign _076_ = ~(_075_ | _073_);
  assign _077_ = ~(_069_ & _068_);
  assign _078_ = ~(_077_ | _073_);
  assign _079_ = _078_ | _076_;
  assign \mchip.slv.wr_down  = _079_ | _074_;
  assign _080_ = io_in[10] & ~(\mchip.slv.wr_down );
  assign _081_ = io_in[13] & ~(_062_);
  assign _082_ = _061_ & io_in[13];
  assign _083_ = _082_ | _081_;
  assign _084_ = _060_ & io_in[13];
  assign _085_ = _059_ & io_in[13];
  assign _086_ = _085_ | _084_;
  assign _087_ = _086_ | _083_;
  assign _088_ = io_in[13] & ~(_027_);
  assign _089_ = _088_ | io_in[1];
  assign _090_ = _072_ | ~(_071_);
  assign _091_ = _070_ & ~(_090_);
  assign _092_ = ~(_090_ | _075_);
  assign _093_ = ~(_092_ | _091_);
  assign _094_ = ~(_093_ | _089_);
  assign _095_ = _087_ & ~(_089_);
  assign _096_ = ~(_090_ | _077_);
  assign _097_ = _096_ & _095_;
  assign _098_ = _097_ | _094_;
  assign _099_ = _093_ & ~(_096_);
  assign _100_ = _098_ & ~(_099_);
  assign _001_ = _087_ ? _100_ : _080_;
  assign _101_ = _066_ & io_in[13];
  assign _102_ = ~(_067_ & io_in[13]);
  assign _103_ = _102_ | _101_;
  assign _104_ = _065_ & io_in[13];
  assign _105_ = _064_ & io_in[13];
  assign _106_ = _105_ | _104_;
  assign _107_ = _106_ | _103_;
  assign _108_ = ~(_088_ & io_in[1]);
  assign _109_ = _108_ | ~(_107_);
  assign _110_ = ~(_107_ | _089_);
  assign _111_ = ~(_110_ & _109_);
  assign \mchip.slv.store  = _078_ & ~(_111_);
  assign _112_ = _072_ | _071_;
  assign _113_ = _070_ & ~(_112_);
  assign _114_ = _089_ | io_in[0];
  assign _115_ = ~(_033_ & io_in[13]);
  assign _116_ = _115_ | _114_;
  assign _117_ = _113_ & ~(_116_);
  assign _118_ = _074_ & ~(_089_);
  assign _119_ = _118_ | _117_;
  assign _120_ = _071_ | ~(_070_);
  assign _121_ = _119_ & ~(_120_);
  assign _122_ = ~(_112_ | _075_);
  assign _123_ = ~(_122_ | _078_);
  assign _124_ = _123_ & ~(_076_);
  assign _125_ = _123_ | _109_;
  assign _126_ = _076_ & ~(_108_);
  assign _127_ = _125_ & ~(_126_);
  assign _128_ = _127_ | _124_;
  assign _129_ = _107_ & ~(_128_);
  assign _000_ = _129_ | _121_;
  assign _130_ = _063_ & io_in[13];
  assign _131_ = ~_089_;
  assign _132_ = _068_ | ~(_069_);
  assign _133_ = _132_ | _112_;
  assign _134_ = _132_ | _073_;
  assign _135_ = ~(_134_ & _133_);
  assign _136_ = _091_ | _074_;
  assign _137_ = _089_ ? _136_ : _135_;
  assign _138_ = _137_ | \mchip.slv.store ;
  assign _139_ = ~(_136_ | _135_);
  assign _140_ = _139_ & ~(_078_);
  assign _141_ = _138_ & ~(_140_);
  assign \mchip.slv.SDA_out  = _130_ & ~(_141_);
  assign _142_ = ~io_in[0];
  assign _143_ = _142_ & ~(_108_);
  assign _144_ = _032_ & io_in[13];
  assign _145_ = _034_ | ~(io_in[13]);
  assign _146_ = _145_ | _142_;
  assign _147_ = io_in[1] ? _146_ : _088_;
  assign \mchip.slv.stop_nextstate  = _144_ ? _147_ : _143_;
  assign _148_ = ~(_145_ & _142_);
  assign _149_ = io_in[1] & ~(_148_);
  assign _150_ = io_in[0] & ~(_089_);
  assign _151_ = _114_ & ~(_150_);
  assign \mchip.slv.start_nextstate  = _115_ ? _149_ : _151_;
  assign _019_ = _129_ & ~(_142_);
  assign _152_ = ~(_035_ & io_in[13]);
  assign \mchip.slv.r1w0  = ~_152_;
  assign _020_ = _129_ & ~(_152_);
  assign \mchip.slv.the_sipo.out [1] = _036_ & io_in[13];
  assign _021_ = \mchip.slv.the_sipo.out [1] & _129_;
  assign \mchip.slv.the_sipo.out [2] = _037_ & io_in[13];
  assign _022_ = \mchip.slv.the_sipo.out [2] & _129_;
  assign \mchip.slv.the_sipo.out [3] = _038_ & io_in[13];
  assign _023_ = \mchip.slv.the_sipo.out [3] & _129_;
  assign _153_ = ~(_039_ & io_in[13]);
  assign \mchip.slv.the_sipo.out [4] = ~_153_;
  assign _024_ = _129_ & ~(_153_);
  assign \mchip.slv.the_sipo.out [5] = _040_ & io_in[13];
  assign _025_ = \mchip.slv.the_sipo.out [5] & _129_;
  assign \mchip.slv.the_sipo.out [6] = _041_ & io_in[13];
  assign _026_ = \mchip.slv.the_sipo.out [6] & _129_;
  assign _015_ = _129_ & ~(_105_);
  assign _154_ = _105_ & _104_;
  assign _155_ = _154_ | ~(_106_);
  assign _016_ = _129_ & ~(_155_);
  assign _156_ = ~_101_;
  assign _157_ = _154_ ^ _156_;
  assign _017_ = _129_ & ~(_157_);
  assign _158_ = _154_ & ~(_156_);
  assign _159_ = _158_ ^ _102_;
  assign _018_ = _129_ & ~(_159_);
  assign _160_ = _080_ & ~(_087_);
  assign _161_ = ~(_058_ & io_in[13]);
  assign _006_ = ~(_161_ | _160_);
  assign _002_ = ~(_160_ | _085_);
  assign _003_ = _085_ ^ _084_;
  assign _162_ = ~_082_;
  assign _163_ = _085_ & _084_;
  assign _164_ = _163_ ^ _162_;
  assign _004_ = ~(_164_ | _160_);
  assign _165_ = _163_ & ~(_162_);
  assign _166_ = _165_ ^ _081_;
  assign _005_ = ~(_166_ | _160_);
  assign _007_ = _160_ & io_in[2];
  assign _167_ = _051_ & io_in[13];
  assign _008_ = _160_ ? io_in[3] : _167_;
  assign _168_ = _052_ & io_in[13];
  assign _009_ = _160_ ? io_in[4] : _168_;
  assign _169_ = _053_ & io_in[13];
  assign _010_ = _160_ ? io_in[5] : _169_;
  assign _170_ = _054_ & io_in[13];
  assign _011_ = _160_ ? io_in[6] : _170_;
  assign _171_ = _055_ & io_in[13];
  assign _012_ = _160_ ? io_in[7] : _171_;
  assign _172_ = _056_ & io_in[13];
  assign _013_ = _160_ ? io_in[8] : _172_;
  assign _173_ = _057_ & io_in[13];
  assign _014_ = _160_ ? io_in[9] : _173_;
  assign _174_ = ~_096_;
  assign _175_ = _089_ | _087_;
  assign _176_ = _175_ & ~(_174_);
  assign _177_ = _176_ | _094_;
  assign \mchip.slv.wr_up  = _177_ & ~(_099_);
  assign _178_ = ~(_042_ & io_in[13]);
  assign \mchip.slv.the_sipo.out [7] = ~_178_;
  assign _179_ = ~_109_;
  assign _180_ = \mchip.slv.the_sipo.out [1] & ~(\mchip.slv.the_sipo.out [2]);
  assign _181_ = _153_ | \mchip.slv.the_sipo.out [3];
  assign _182_ = _180_ & ~(_181_);
  assign _183_ = \mchip.slv.the_sipo.out [6] | \mchip.slv.the_sipo.out [5];
  assign _184_ = _183_ | _178_;
  assign _185_ = _182_ & ~(_184_);
  assign _186_ = ~(_185_ | _107_);
  assign _187_ = _186_ & ~(_179_);
  assign _188_ = _122_ & ~(_187_);
  assign _189_ = _188_ | _117_;
  assign _190_ = _089_ & ~(_133_);
  assign _191_ = _190_ | _189_;
  assign _192_ = _108_ & _076_;
  assign _193_ = _192_ | _118_;
  assign _194_ = _089_ & ~(_134_);
  assign _195_ = _194_ | _193_;
  assign _196_ = _089_ ? _092_ : _091_;
  assign _197_ = _096_ & ~(_175_);
  assign _198_ = io_in[0] & ~(_108_);
  assign _199_ = ~(_132_ | _090_);
  assign _200_ = _199_ & ~(_198_);
  assign _201_ = _200_ | _197_;
  assign _202_ = _201_ | _196_;
  assign _203_ = _202_ | _195_;
  assign _204_ = _203_ | _191_;
  assign _205_ = ~(_072_ & _071_);
  assign \mchip.slv.nextstate [0] = _205_ & _204_;
  assign _206_ = _198_ | _143_;
  assign _207_ = _199_ & ~(_206_);
  assign _208_ = _174_ & ~(_207_);
  assign _209_ = _092_ & ~(_089_);
  assign _210_ = _208_ & ~(_209_);
  assign _211_ = _146_ | ~(io_in[1]);
  assign _212_ = _211_ & ~(_110_);
  assign _213_ = _109_ & ~(_212_);
  assign _214_ = _078_ & ~(_213_);
  assign _215_ = _214_ | _194_;
  assign _216_ = _215_ | _126_;
  assign _217_ = _210_ & ~(_216_);
  assign _218_ = _107_ | ~(_109_);
  assign _219_ = _122_ & ~(_218_);
  assign _220_ = ~(_112_ | _077_);
  assign _221_ = _144_ & ~(_211_);
  assign _222_ = _220_ & ~(_221_);
  assign _223_ = _222_ | _190_;
  assign _224_ = _223_ | _219_;
  assign _225_ = _217_ & ~(_224_);
  assign \mchip.slv.nextstate [1] = _205_ & ~(_225_);
  assign _226_ = ~(_076_ | _074_);
  assign _227_ = _211_ | _110_;
  assign _228_ = _109_ & ~(_227_);
  assign _229_ = _078_ & ~(_228_);
  assign _230_ = _229_ | _194_;
  assign _231_ = _226_ & ~(_230_);
  assign _232_ = _107_ | ~(_185_);
  assign _233_ = _232_ | _152_;
  assign _234_ = _233_ | _186_;
  assign _235_ = _234_ | _179_;
  assign _236_ = _122_ & ~(_235_);
  assign _237_ = _131_ & ~(_133_);
  assign _238_ = _237_ | _236_;
  assign _239_ = _231_ & ~(_238_);
  assign \mchip.slv.nextstate [2] = _205_ & ~(_239_);
  assign _240_ = _200_ | _096_;
  assign _241_ = _093_ & ~(_240_);
  assign _242_ = _131_ & ~(_134_);
  assign _243_ = _241_ & ~(_242_);
  assign \mchip.slv.nextstate [3] = _205_ & ~(_243_);
  assign \mchip.slv.writeOK  = ~(_087_ | \mchip.slv.wr_down );
  assign io_out[2] = _043_ & io_in[13];
  assign io_out[3] = _044_ & io_in[13];
  assign io_out[4] = _045_ & io_in[13];
  assign io_out[5] = _046_ & io_in[13];
  assign io_out[6] = _047_ & io_in[13];
  assign io_out[7] = _048_ & io_in[13];
  assign io_out[8] = _049_ & io_in[13];
  assign io_out[9] = _050_ & io_in[13];
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:171.5-184.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _027_ <= 1'h1;
    else _027_ <= io_in[1];
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:394.5-399.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _028_ <= 1'h0;
    else _028_ <= \mchip.slv.nextstate [0];
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:394.5-399.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _029_ <= 1'h0;
    else _029_ <= \mchip.slv.nextstate [1];
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:394.5-399.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _030_ <= 1'h0;
    else _030_ <= \mchip.slv.nextstate [2];
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:394.5-399.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _031_ <= 1'h0;
    else _031_ <= \mchip.slv.nextstate [3];
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:171.5-184.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _032_ <= 1'h0;
    else _032_ <= \mchip.slv.stop_nextstate ;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:171.5-184.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _033_ <= 1'h0;
    else _033_ <= \mchip.slv.start_nextstate ;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:171.5-184.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _034_ <= 1'h1;
    else _034_ <= io_in[0];
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _035_ <= 1'h0;
    else if (_000_) _035_ <= _019_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _036_ <= 1'h0;
    else if (_000_) _036_ <= _020_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _037_ <= 1'h0;
    else if (_000_) _037_ <= _021_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _038_ <= 1'h0;
    else if (_000_) _038_ <= _022_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _039_ <= 1'h0;
    else if (_000_) _039_ <= _023_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _040_ <= 1'h0;
    else if (_000_) _040_ <= _024_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _041_ <= 1'h0;
    else if (_000_) _041_ <= _025_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _042_ <= 1'h0;
    else if (_000_) _042_ <= _026_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:199.14-200.38|d11_zhexic_i2cdriver/src/chip.sv:485.5-491.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _043_ <= 1'h0;
    else if (\mchip.slv.store ) _043_ <= \mchip.slv.r1w0 ;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:199.14-200.38|d11_zhexic_i2cdriver/src/chip.sv:485.5-491.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _044_ <= 1'h0;
    else if (\mchip.slv.store ) _044_ <= \mchip.slv.the_sipo.out [1];
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:199.14-200.38|d11_zhexic_i2cdriver/src/chip.sv:485.5-491.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _045_ <= 1'h0;
    else if (\mchip.slv.store ) _045_ <= \mchip.slv.the_sipo.out [2];
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:199.14-200.38|d11_zhexic_i2cdriver/src/chip.sv:485.5-491.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _046_ <= 1'h0;
    else if (\mchip.slv.store ) _046_ <= \mchip.slv.the_sipo.out [3];
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:199.14-200.38|d11_zhexic_i2cdriver/src/chip.sv:485.5-491.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _047_ <= 1'h0;
    else if (\mchip.slv.store ) _047_ <= \mchip.slv.the_sipo.out [4];
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:199.14-200.38|d11_zhexic_i2cdriver/src/chip.sv:485.5-491.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _048_ <= 1'h0;
    else if (\mchip.slv.store ) _048_ <= \mchip.slv.the_sipo.out [5];
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:199.14-200.38|d11_zhexic_i2cdriver/src/chip.sv:485.5-491.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _049_ <= 1'h0;
    else if (\mchip.slv.store ) _049_ <= \mchip.slv.the_sipo.out [6];
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:199.14-200.38|d11_zhexic_i2cdriver/src/chip.sv:485.5-491.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _050_ <= 1'h0;
    else if (\mchip.slv.store ) _050_ <= \mchip.slv.the_sipo.out [7];
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _051_ <= 1'h0;
    else if (_001_) _051_ <= _007_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _052_ <= 1'h0;
    else if (_001_) _052_ <= _008_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _053_ <= 1'h0;
    else if (_001_) _053_ <= _009_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _054_ <= 1'h0;
    else if (_001_) _054_ <= _010_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _055_ <= 1'h0;
    else if (_001_) _055_ <= _011_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _056_ <= 1'h0;
    else if (_001_) _056_ <= _012_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _057_ <= 1'h0;
    else if (_001_) _057_ <= _013_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _058_ <= 1'h0;
    else if (_001_) _058_ <= _014_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _059_ <= 1'h0;
    else if (_001_) _059_ <= _002_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _060_ <= 1'h0;
    else if (_001_) _060_ <= _003_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _061_ <= 1'h0;
    else if (_001_) _061_ <= _004_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _062_ <= 1'h1;
    else if (_001_) _062_ <= _005_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:205.10-206.73|d11_zhexic_i2cdriver/src/chip.sv:456.5-472.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _063_ <= 1'h0;
    else if (_001_) _063_ <= _006_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _064_ <= 1'h0;
    else if (_000_) _064_ <= _015_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _065_ <= 1'h0;
    else if (_000_) _065_ <= _016_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _066_ <= 1'h0;
    else if (_000_) _066_ <= _017_;
  /* \always_ff  = 32'd1 */
  /* src = "d11_zhexic_i2cdriver/src/toplevel_chip.v:10.13-15.6|d11_zhexic_i2cdriver/src/chip.sv:193.10-194.71|d11_zhexic_i2cdriver/src/chip.sv:418.5-433.8|d11_zhexic_i2cdriver/src/chip.sv:10.15-13.53" */
  always @(posedge io_in[12])
    if (!io_in[13]) _067_ <= 1'h0;
    else if (_000_) _067_ <= _018_;
  assign { io_out[13:10], io_out[1:0] } = { 2'h0, \mchip.slv.wr_down , \mchip.slv.writeOK , \mchip.slv.wr_up , \mchip.slv.SDA_out  };
  assign \mchip.clock  = io_in[12];
  assign \mchip.io_in  = io_in[11:0];
  assign \mchip.io_out  = { \mchip.slv.wr_down , \mchip.slv.writeOK , io_out[9:2], \mchip.slv.wr_up , \mchip.slv.SDA_out  };
  assign \mchip.reset  = io_in[13];
  assign \mchip.slv.SCL  = io_in[1];
  assign \mchip.slv.SDA_in  = io_in[0];
  assign \mchip.slv.clock  = io_in[12];
  assign \mchip.slv.data_in  = io_in[9:2];
  assign \mchip.slv.data_incoming  = io_in[10];
  assign \mchip.slv.data_out  = io_out[9:2];
  assign \mchip.slv.register_out  = io_out[9:2];
  assign \mchip.slv.reset  = io_in[13];
  assign \mchip.slv.scl_high  = io_in[1];
  assign \mchip.slv.scl_nextstate  = io_in[1];
  assign \mchip.slv.sda_high  = io_in[0];
  assign \mchip.slv.sda_nextstate  = io_in[0];
  assign \mchip.slv.sipo_out  = { \mchip.slv.the_sipo.out [7:1], \mchip.slv.r1w0  };
  assign \mchip.slv.the_piso.clock  = io_in[12];
  assign \mchip.slv.the_piso.data_in  = io_in[9:2];
  assign \mchip.slv.the_piso.reset  = io_in[13];
  assign \mchip.slv.the_reg.clock  = io_in[12];
  assign \mchip.slv.the_reg.enable  = \mchip.slv.store ;
  assign \mchip.slv.the_reg.in  = { \mchip.slv.the_sipo.out [7:1], \mchip.slv.r1w0  };
  assign \mchip.slv.the_reg.out  = io_out[9:2];
  assign \mchip.slv.the_reg.reset  = io_in[13];
  assign \mchip.slv.the_sipo.clock  = io_in[12];
  assign \mchip.slv.the_sipo.data_in  = io_in[0];
  assign \mchip.slv.the_sipo.out [0] = \mchip.slv.r1w0 ;
  assign \mchip.slv.the_sipo.reset  = io_in[13];
endmodule
